#ifndef VOLOOP_BSP_DEF_H
#define VOLOOP_BSP_DEF_H

typedef enum {
    VOLOOP_BSP_OK = 0x00U,
    VOLOOP_BSP_ERROR,
    VOLOOP_BSP_INVALID_PARAM,
    VOLOOP_BSP_INVALID_STATE,
    VOLOOP_BSP_BUSY,
    VOLOOP_BSP_TIMEOUT
} VOLOOP_BSP_StatusTypeDef;

#endif
