/**
 * @file voloop_3phOffInv.h
 * @brief Three-phase off-grid inverter control API.
 */
#ifndef VOLOOP_3PH_OFF_INV_H
#define VOLOOP_3PH_OFF_INV_H

#include "voloop_def.h"
#include "voloop_nco.h"
#include "voloop_pid.h"

#include <stdint.h>

/**
 * @defgroup VOLOOP_3PH_OFF_INV Three-Phase Off-Grid Inverter
 * @ingroup VOLOOP_CORE
 * @brief Three-phase, three-wire off-grid inverter control APIs.
 *
 * The module targets a two-level inverter with three complementary half-bridge
 * legs and no independently controlled neutral leg. Board-specific code owns
 * ADC acquisition, complementary PWM generation, dead time, and emergency
 * hardware shutdown.
 *
 * ::VOLOOP_3phOffInv_Sync is called once per control-loop period. The
 * implementation uses cascaded synchronous-frame control: d-q voltage
 * controllers generate d-q inductor-current references, and d-q current
 * controllers generate modulation corrections around measured output-voltage
 * feedforward. Min-max common-mode injection produces three bridge-leg duty
 * recommendations with space-vector-equivalent DC-bus utilization.
 *
 * Every exported duty is the upper-switch duty of its corresponding
 * complementary half bridge. The lower-switch command is generated by board
 * hardware as:
 *
 * @code
 * lowerSwitchDuty = 1.0f - upperSwitchDuty;
 * @endcode
 *
 * ## Basic usage
 *
 * 1. Prepare an ::NCO_InitTypeDef object.
 * 2. Fill a ::ThreePhOffInv_ConfigTypeDef with protection thresholds.
 * 3. Fill a ::ThreePhOffInv_InitTypeDef and call
 *    ::VOLOOP_3phOffInv_Init.
 * 4. Optionally change the fundamental frequency with
 *    ::VOLOOP_3phOffInv_SetFrequency.
 * 5. Call ::VOLOOP_3phOffInv_Start.
 * 6. Call ::VOLOOP_3phOffInv_Sync at the configured NCO trigger frequency.
 * 7. Apply the returned bridge-leg recommendations in board-specific code.
 *
 * @{
 */

/**
 * @brief Three-phase inverter measured input sample.
 *
 * The interface uses two line-to-line voltages and two phase currents because
 * the target power stage is a three-wire system. The module reconstructs the
 * remaining quantities as:
 *
 * @code
 * LineVoltageAC = LineVoltageAB + LineVoltageBC;
 * PhaseCurrentB = -(PhaseCurrentA + PhaseCurrentC);
 * @endcode
 *
 * Voltage and current values are signed instantaneous samples. Positive phase
 * current flows from the inverter bridge through the filter inductor toward
 * the load.
 */
typedef struct {
    float BusVoltage;    /**< DC-link voltage sample from ADC channel 12. */
    float LineVoltageAB; /**< Signed A-to-B line-voltage sample from ADC channel 2. */
    float LineVoltageBC; /**< Signed B-to-C line-voltage sample from ADC channel 8. */
    float PhaseCurrentA; /**< Signed phase-A output-current sample from ADC channel 3. */
    float PhaseCurrentC; /**< Signed phase-C output-current sample from ADC channel 9. */
} ThreePhOffInv_InputTypeDef;

/**
 * @brief Three-phase inverter PWM output recommendation.
 *
 * Each duty is the upper-switch duty of one complementary half bridge. Board
 * code must disable both switches of a leg when its PWM state is
 * ::VOLOOP_PWM_DISABLED.
 *
 * The board-level PWM mapping is:
 * - PWMA drives the phase-A bridge leg.
 * - PWMB drives the phase-B bridge leg.
 * - PWMC drives the phase-C bridge leg.
 */
typedef struct {
    VOLOOP_DEF_PwmStateTypeDef PhaseAPwmState; /**< PWMA/phase-A bridge-leg state. */
    float PhaseADuty;                          /**< PWMA/phase-A upper-switch duty in [0, 1]. */
    VOLOOP_DEF_PwmStateTypeDef PhaseBPwmState; /**< PWMB/phase-B bridge-leg state. */
    float PhaseBDuty;                          /**< PWMB/phase-B upper-switch duty in [0, 1]. */
    VOLOOP_DEF_PwmStateTypeDef PhaseCPwmState; /**< PWMC/phase-C bridge-leg state. */
    float PhaseCDuty;                          /**< PWMC/phase-C upper-switch duty in [0, 1]. */
} ThreePhOffInv_OutputTypeDef;

/**
 * @brief Three-phase inverter protection configuration.
 *
 * All thresholds are signed-sample magnitude limits except the DC-link
 * thresholds. A measured value exactly equal to a threshold remains valid.
 */
typedef struct {
    float LineOverVoltageThreshold;  /**< Absolute line-voltage fault threshold. */
    float PhaseOverCurrentThreshold; /**< Absolute phase-current fault threshold. */
    float BusUnderVoltageThreshold;  /**< DC-link under-voltage fault threshold. */
    float BusOverVoltageThreshold;   /**< DC-link over-voltage fault threshold. */
} ThreePhOffInv_ConfigTypeDef;

/**
 * @brief Three-phase inverter initialization parameters.
 *
 * The NCO trigger frequency is also the required call frequency of
 * ::VOLOOP_3phOffInv_Sync. The NCO and protection configuration objects are
 * consumed and copied by ::VOLOOP_3phOffInv_Init and do not need to remain
 * alive afterward. NCO configuration validation is delegated to
 * ::VOLOOP_NCO_Init.
 *
 * All four d-q controller configurations are consumed by
 * ::VOLOOP_3phOffInv_Init and copied into controller handles owned by the
 * inverter handle. Voltage-controller outputs are current references in
 * amperes. Current-controller outputs are normalized modulation corrections.
 */
typedef struct {
    const NCO_InitTypeDef* NCOInit;            /**< Internal NCO initialization. */
    const ThreePhOffInv_ConfigTypeDef* Config; /**< Protection configuration. */
    const PID_InitTypeDef* VoltageDControllerInit; /**< D-axis voltage-controller initialization. */
    const PID_InitTypeDef* VoltageQControllerInit; /**< Q-axis voltage-controller initialization. */
    const PID_InitTypeDef* CurrentDControllerInit; /**< D-axis current-controller initialization. */
    const PID_InitTypeDef* CurrentQControllerInit; /**< Q-axis current-controller initialization. */
} ThreePhOffInv_InitTypeDef;

/**
 * @brief Three-phase inverter runtime state.
 */
typedef enum {
    THREEPHOFFINV_RESET = 0U, /**< Zero-initialized, reset, or deinitialized handle. */
    THREEPHOFFINV_DISABLED,   /**< Initialized with all power outputs disabled. */
    THREEPHOFFINV_RUNNING,    /**< Running and accepting sync updates. */
    THREEPHOFFINV_ERROR       /**< Latched inverter or child-module fault. */
} ThreePhOffInv_StateTypeDef;

/**
 * @brief Three-phase inverter latched fault code.
 */
typedef enum {
    THREEPHOFFINV_FAULT_NONE = 0U,         /**< No latched fault. */
    THREEPHOFFINV_FAULT_LINE_OVERVOLTAGE,  /**< At least one line voltage exceeded its limit. */
    THREEPHOFFINV_FAULT_PHASE_OVERCURRENT, /**< At least one phase current exceeded its limit. */
    THREEPHOFFINV_FAULT_BUS_UNDERVOLTAGE,  /**< DC-link voltage fell below its lower limit. */
    THREEPHOFFINV_FAULT_BUS_OVERVOLTAGE,   /**< DC-link voltage exceeded its upper limit. */
    THREEPHOFFINV_FAULT_INVALID_SAMPLE,    /**< A measured or reconstructed sample was invalid. */
    THREEPHOFFINV_FAULT_NCO,               /**< The internal NCO reported a runtime failure. */
    THREEPHOFFINV_FAULT_INVALID            /**< Invalid value returned for an invalid handle. */
} ThreePhOffInv_FaultCodeTypeDef;

/**
 * @brief Three-phase inverter runtime handle.
 *
 * Applications should treat these members as read-only implementation state
 * and use the public API to operate the module.
 */
typedef struct {
    ThreePhOffInv_ConfigTypeDef Config;       /**< Copied protection configuration. */
    NCO_HandleTypeDef NCO;                    /**< Internal fundamental-phase generator. */
    PID_HandleTypeDef VoltageDController;     /**< D-axis voltage-loop controller. */
    PID_HandleTypeDef VoltageQController;     /**< Q-axis voltage-loop controller. */
    PID_HandleTypeDef CurrentDController;     /**< D-axis current-loop controller. */
    PID_HandleTypeDef CurrentQController;     /**< Q-axis current-loop controller. */
    float TargetLineVoltagePeak;              /**< Requested line-to-line voltage peak. */
    float InitialPhaseRad;                    /**< Phase restored by each successful start. */
    int32_t OutputPhaseQ31;                   /**< Phase used for the latest output command. */
    ThreePhOffInv_StateTypeDef State;         /**< Current runtime state. */
    ThreePhOffInv_FaultCodeTypeDef FaultCode; /**< Current latched fault code. */
} ThreePhOffInv_HandleTypeDef;

/**
 * @brief Initialize a three-phase off-grid inverter.
 *
 * This function validates and copies the inverter protection configuration,
 * initializes the owned d-q voltage and current controllers, delegates NCO
 * configuration validation and initialization to ::VOLOOP_NCO_Init, and enters
 * ::THREEPHOFFINV_DISABLED.
 *
 * @param handle Inverter handle to initialize.
 * @param init Initialization parameters.
 * @return ::VOLOOP_OK on success, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_3phOffInv_Init(ThreePhOffInv_HandleTypeDef* handle,
                                           const ThreePhOffInv_InitTypeDef* init);

/**
 * @brief Deinitialize a three-phase off-grid inverter.
 *
 * @param handle Inverter handle.
 * @return ::VOLOOP_OK on success, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_3phOffInv_DeInit(ThreePhOffInv_HandleTypeDef* handle);

/**
 * @brief Start cascaded closed-loop three-phase output.
 *
 * Every successful start resets all four d-q controllers and restores the NCO
 * to the initial phase supplied during initialization. The first later sync
 * call therefore generates its output from that exact phase. Calling start
 * while already running is idempotent and does not reset controller state.
 *
 * @param handle Inverter handle.
 * @return ::VOLOOP_OK on success, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_3phOffInv_Start(ThreePhOffInv_HandleTypeDef* handle);

/**
 * @brief Stop three-phase output, stop the internal NCO, and reset all d-q controllers.
 *
 * @param handle Inverter handle.
 * @return ::VOLOOP_OK on success, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_3phOffInv_Stop(ThreePhOffInv_HandleTypeDef* handle);

/**
 * @brief Clear a latched fault.
 *
 * This operation is valid only in ::THREEPHOFFINV_ERROR or
 * ::THREEPHOFFINV_DISABLED. Fault entry preserves all four controller
 * histories for diagnosis. A successful clear resets those histories, returns
 * the module to ::THREEPHOFFINV_DISABLED, and does not restart power output.
 *
 * @param handle Inverter handle.
 * @return ::VOLOOP_OK on success, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_3phOffInv_ClearFaultCode(ThreePhOffInv_HandleTypeDef* handle);

/**
 * @brief Set the fundamental output frequency.
 *
 * This function is valid in ::THREEPHOFFINV_DISABLED and
 * ::THREEPHOFFINV_RUNNING. It changes only the NCO phase increment and does
 * not reset the current phase.
 *
 * @param handle Inverter handle.
 * @param frequency Fundamental frequency in Hz.
 * @return ::VOLOOP_OK on success, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_3phOffInv_SetFrequency(ThreePhOffInv_HandleTypeDef* handle,
                                                   float frequency);

/**
 * @brief Set the target line-to-line output-voltage peak.
 *
 * This function is valid in ::THREEPHOFFINV_DISABLED and
 * ::THREEPHOFFINV_RUNNING. A zero target is valid. The target must not exceed
 * ::ThreePhOffInv_ConfigTypeDef::LineOverVoltageThreshold.
 *
 * @param handle Inverter handle.
 * @param lineVoltagePeak Target line-to-line voltage peak.
 * @return ::VOLOOP_OK on success, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_3phOffInv_SetLineVoltagePeak(
    ThreePhOffInv_HandleTypeDef* handle,
    float lineVoltagePeak);

/**
 * @brief Get the current inverter state.
 *
 * @param handle Inverter handle.
 * @return Current state, or ::THREEPHOFFINV_ERROR if @p handle is NULL.
 */
ThreePhOffInv_StateTypeDef VOLOOP_3phOffInv_GetState(const ThreePhOffInv_HandleTypeDef* handle);

/**
 * @brief Get the current latched fault code.
 *
 * @param handle Inverter handle.
 * @return Current fault code, or ::THREEPHOFFINV_FAULT_INVALID if @p handle is
 *         NULL.
 */
ThreePhOffInv_FaultCodeTypeDef
VOLOOP_3phOffInv_GetFaultCode(const ThreePhOffInv_HandleTypeDef* handle);

/**
 * @brief Get the configured fundamental output frequency.
 *
 * @param handle Inverter handle.
 * @return Current frequency in Hz, or 0.0f if @p handle is NULL.
 */
float VOLOOP_3phOffInv_GetFrequency(const ThreePhOffInv_HandleTypeDef* handle);

/**
 * @brief Get the phase used for the latest output command.
 *
 * Before the first running sync call, this is the configured initial phase.
 *
 * @param handle Inverter handle.
 * @return Latest output phase in Q1.31 format, or 0 if @p handle is NULL.
 */
int32_t VOLOOP_3phOffInv_GetPhaseQ31(const ThreePhOffInv_HandleTypeDef* handle);

/**
 * @brief Run one cascaded d-q voltage/current control update.
 *
 * The output is first initialized to a safe disabled recommendation. While
 * running, this function validates all five measured samples, reconstructs
 * line voltage AC and phase current B, and applies configured protection. It
 * transforms measured phase voltage and inductor current to the synchronous
 * d-q frame. The voltage controllers generate current references limited by
 * the configured phase-overcurrent threshold; the current controllers generate
 * modulation corrections around measured output-voltage feedforward. The
 * resulting modulation vector is limited to 2/sqrt(3), inverse transformed,
 * and converted to bridge duties with min-max common-mode injection. The first
 * update after each start uses the configured initial phase; the NCO is
 * advanced for the following update.
 *
 * A newly detected protection or child-module fault disables all bridge legs,
 * stops the NCO, latches ::THREEPHOFFINV_ERROR, and returns ::VOLOOP_ERROR.
 * While disabled, the function leaves all bridge legs disabled and returns
 * ::VOLOOP_OK.
 *
 * @param handle Inverter handle.
 * @param input Measured DC-link, line-voltage, and phase-current sample.
 * @param output Three-phase bridge-leg output recommendation.
 * @return ::VOLOOP_OK on a successful or disabled update,
 *         ::VOLOOP_ERROR when a new fault is latched, otherwise a voloop
 *         status code.
 */
VOLOOP_StatusTypeDef VOLOOP_3phOffInv_Sync(ThreePhOffInv_HandleTypeDef* handle,
                                           const ThreePhOffInv_InputTypeDef* input,
                                           ThreePhOffInv_OutputTypeDef* output);

/** @} */

#endif /* VOLOOP_3PH_OFF_INV_H */
