/**
 * @file voloop_buck.h
 * @brief Buck converter control API.
 */
#ifndef VOLOOP_BUCK_H
#define VOLOOP_BUCK_H

#include "voloop_def.h"
#include "voloop_pid.h"

/**
 * @defgroup VOLOOP_BUCK Buck Converter
 * @ingroup VOLOOP_CORE
 * @brief Buck converter voltage/current control APIs built from cascaded PID loops.
 *
 * The Buck module combines an outer output-voltage loop and inner inductor-current
 * loop to generate PWM duty recommendations from measured output voltage and
 * inductor current. It tracks runtime state and fault conditions, but does not
 * directly read ADC values or drive PWM hardware.
 *
 * ## Basic usage
 *
 * 1. Prepare output-voltage and inductor-current ::PID_InitTypeDef objects.
 * 2. Fill a ::Buck_InitTypeDef object.
 * 3. Call ::VOLOOP_Buck_Init and ::VOLOOP_Buck_Start.
 * 4. Set the target voltage and current limit with ::VOLOOP_Buck_SetValue.
 * 5. Call ::VOLOOP_Buck_Sync once per control-loop sample with measured inputs.
 * 6. Apply the returned ::Buck_OutputTypeDef PWM recommendation in board code.
 *
 * @{
 */

/**
 * @brief Buck converter initialization parameters.
 */
typedef struct {
    PID_InitTypeDef* OutPutVoltagePIDInit; /**< Output-voltage PID initialization. */
    PID_InitTypeDef* InductorCurrentPIDInit; /**< Inductor-current PID initialization. */
} Buck_InitTypeDef;

/**
 * @brief Buck converter measured input sample.
 */
typedef struct {
    float OutputVoltage;   /**< Measured output voltage. */
    float InductorCurrent; /**< Measured inductor current. */
} Buck_InputTypeDef;

/**
 * @brief Buck converter PWM output recommendation.
 */
typedef struct {
    VOLOOP_DEF_PwmStateTypeDef PwmState; /**< Recommended PWM output state. */
    float Duty; /**< Recommended duty command, normally in [BUCK_MIN_DUTY, BUCK_MAX_DUTY]. */
} Buck_OutputTypeDef;

/**
 * @brief Buck converter runtime state.
 */
typedef enum {
    BUCK_ERROR = 0U, /**< Error state, usually caused by protection or invalid operation. */
    BUCK_DISABLED,   /**< Buck controller is initialized but not running. */
    BUCK_CVMODE,     /**< Buck controller is running in constant-voltage mode. */
    BUCK_CCMODE      /**< Buck controller is running in current-limit mode. */
} Buck_StateTypeDef;

/**
 * @brief Buck converter protection fault code.
 */
typedef enum {
    BUCK_INVALID = 0U, /**< Invalid fault code, also returned for invalid handles. */
    BUCK_NOERROR,      /**< No active fault. */
    BUCK_OCP,          /**< Over-current protection fault. */
    BUCK_OVP           /**< Over-voltage protection fault. */
} Buck_FaultCodeTypeDef;

/**
 * @brief Buck converter runtime handle.
 *
 * The handle owns the voltage and current PID controllers, target voltage,
 * current limit, fault state, runtime mode, and latest duty recommendation.
 */
typedef struct {
    Buck_InitTypeDef Init; /**< Initialization parameters used to create the handle. */
    PID_HandleTypeDef OutPutVoltagePID; /**< Outer output-voltage PID controller. */
    PID_HandleTypeDef InductorCurrentPID; /**< Inner inductor-current PID controller. */
    Buck_StateTypeDef State; /**< Current Buck controller state. */
    Buck_FaultCodeTypeDef FaultCode; /**< Current protection fault code. */
    float TargetOutputVoltage; /**< Target output voltage. */
    float MaxInductorCurrent; /**< Maximum target inductor current generated by the voltage loop. */
    float Duty; /**< Latest duty recommendation. */
} Buck_HandleTypeDef;

/**
 * @brief Output over-voltage protection threshold.
 */
#define BUCK_OVTHRESHOLD 50.0f

/**
 * @brief Inductor over-current protection threshold.
 */
#define BUCK_OCTHRESHOLD 5.0f

/**
 * @brief Maximum generated PWM duty.
 */
#define BUCK_MAX_DUTY 0.90f

/**
 * @brief Minimum generated PWM duty while running.
 */
#define BUCK_MIN_DUTY 0.10f

/**
 * @brief Initialize a Buck controller.
 *
 * @param handle Buck handle to initialize.
 * @param init Initialization parameters.
 * @return VOLOOP_OK on success, otherwise a VOLOOP error code.
 */
VOLOOP_StatusTypeDef VOLOOP_Buck_Init(Buck_HandleTypeDef* handle, Buck_InitTypeDef* init);

/**
 * @brief Deinitialize a Buck controller.
 *
 * @param handle Buck handle to clear.
 * @return VOLOOP_OK on success, otherwise a VOLOOP error code.
 */
VOLOOP_StatusTypeDef VOLOOP_Buck_DeInit(Buck_HandleTypeDef* handle);

/**
 * @brief Start Buck control.
 *
 * This resets both PID controllers and moves the controller to BUCK_CVMODE.
 *
 * @param handle Buck handle.
 * @return VOLOOP_OK on success, otherwise a VOLOOP error code.
 */
VOLOOP_StatusTypeDef VOLOOP_Buck_Start(Buck_HandleTypeDef* handle);

/**
 * @brief Stop Buck control.
 *
 * This moves the controller to BUCK_DISABLED. Calling this function while
 * already disabled succeeds without changing state.
 *
 * @param handle Buck handle.
 * @return VOLOOP_OK on success, otherwise a VOLOOP error code.
 */
VOLOOP_StatusTypeDef VOLOOP_Buck_Stop(Buck_HandleTypeDef* handle);

/**
 * @brief Get the current Buck runtime state.
 *
 * @param handle Buck handle.
 * @return Current Buck state, or BUCK_ERROR if @p handle is NULL.
 */
Buck_StateTypeDef VOLOOP_Buck_GetState(Buck_HandleTypeDef* handle);

/**
 * @brief Get the current Buck fault code.
 *
 * @param handle Buck handle.
 * @return Current fault code, or BUCK_INVALID if @p handle is NULL.
 */
Buck_FaultCodeTypeDef VOLOOP_Buck_GetFaultCode(Buck_HandleTypeDef* handle);

/**
 * @brief Clear the current Buck fault code.
 *
 * @param handle Buck handle.
 * @return VOLOOP_OK on success, otherwise a VOLOOP error code.
 *
 * @note This function is valid only while the controller is BUCK_ERROR or
 *       BUCK_DISABLED. The controller returns to BUCK_DISABLED on success.
 */
VOLOOP_StatusTypeDef VOLOOP_Buck_ClearFaultCode(Buck_HandleTypeDef* handle);

/**
 * @brief Set the target output voltage and current limit.
 *
 * @param handle Buck handle.
 * @param Voltage Target output voltage.
 * @param Current Maximum inductor current command allowed from the voltage loop.
 * @return VOLOOP_OK on success, otherwise a VOLOOP error code.
 */
VOLOOP_StatusTypeDef VOLOOP_Buck_SetValue(Buck_HandleTypeDef* handle, float Voltage, float Current);

/**
 * @brief Get the latest Buck duty recommendation.
 *
 * @param handle Buck handle.
 * @return Latest duty recommendation, or 0.0f if @p handle is NULL.
 */
float VOLOOP_Buck_GetDuty(Buck_HandleTypeDef* handle);

/**
 * @brief Run one Buck control-loop update.
 *
 * This function checks over-current and over-voltage protection, computes the
 * target inductor current from the voltage loop, computes the PWM duty from
 * the current loop, and writes the PWM recommendation to @p output.
 *
 * @param handle Buck handle.
 * @param input Measured voltage and current input.
 * @param output PWM output recommendation to write.
 * @return VOLOOP_OK on success or disabled-output recommendation, VOLOOP_ERROR
 *         on protection fault, otherwise a VOLOOP error code.
 *
 * @note If the controller is BUCK_DISABLED, @p output is written with
 *       VOLOOP_PWM_DISABLED and zero duty, and the function returns VOLOOP_OK.
 * @note If the controller is BUCK_ERROR, @p output is written with
 *       VOLOOP_PWM_DISABLED and zero duty, and the function returns
 *       VOLOOP_INVALID_STATE.
 */
VOLOOP_StatusTypeDef VOLOOP_Buck_Sync(Buck_HandleTypeDef* handle,
                                      const Buck_InputTypeDef* input,
                                      Buck_OutputTypeDef* output);

/** @} */

#endif /* VOLOOP_BUCK_H */
