/**
 * @file voloop_pfc.h
 * @brief Single-phase totem-pole PFC control API.
 */
#ifndef VOLOOP_PFC_H
#define VOLOOP_PFC_H

#include "voloop_def.h"
#include "voloop_pid.h"
#include "voloop_pll.h"

#include <stdint.h>

/**
 * @defgroup VOLOOP_PFC Totem-Pole PFC
 * @ingroup VOLOOP_CORE
 * @brief Configurable single-phase totem-pole PFC control module.
 *
 * The PFC module is independent of ADC, PWM, GPIO, and dead-time hardware.
 * Application code supplies signed grid voltage/current and DC-bus voltage
 * samples to ::VOLOOP_PFC_Sync, then applies the returned left- and right-leg
 * recommendations to two complementary half bridges.
 *
 * Every duty value exported by this module is the upper-switch duty of the
 * corresponding half bridge. The lower-switch duty is generated by board
 * hardware as:
 *
 * @code
 * lowerSwitchDuty = 1.0f - upperSwitchDuty;
 * @endcode
 *
 * The PLL starts during ::VOLOOP_PFC_Init and continues to run while PFC power
 * output is disabled. ::VOLOOP_PFC_Start and ::VOLOOP_PFC_Stop therefore
 * control only the PFC power-output path and do not restart or stop the PLL.
 *
 * ::VOLOOP_PFC_Sync is called at the configured control-loop frequency. The
 * PLL, DC-bus voltage PI, grid-current PI, and active-state protection all run
 * once per call at the same frequency.
 *
 * All hardware-dependent limits are supplied through ::PFC_ConfigTypeDef.
 * This header does not define default voltage, current, or duty thresholds.
 *
 * ## Basic usage
 *
 * 1. Prepare a ::PLL_InitTypeDef and two PI-configured ::PID_InitTypeDef objects.
 * 2. Fill a ::PFC_ConfigTypeDef with the power-stage limits.
 * 3. Fill a ::PFC_InitTypeDef and call ::VOLOOP_PFC_Init.
 * 4. Call ::VOLOOP_PFC_Sync continuously so the PLL can acquire and track.
 * 5. Set the DC-bus target and current limit with ::VOLOOP_PFC_SetValue.
 * 6. Call ::VOLOOP_PFC_Start to permit PFC power output after PLL lock.
 * 7. Apply the returned ::PFC_OutputTypeDef in board-specific code.
 *
 * @{
 */

/**
 * @brief PFC measured input sample.
 *
 * Grid voltage and current use a signed convention. Positive voltage and
 * current represent the positive grid half-cycle; negative values represent
 * the negative grid half-cycle.
 */
typedef struct {
    float GridVoltage; /**< Signed grid-voltage sample in volts. */
    float GridCurrent; /**< Signed grid/input-current sample in amperes. */
    float BusVoltage;  /**< DC-bus voltage sample in volts. */
} PFC_InputTypeDef;

/**
 * @brief PFC complementary-half-bridge output recommendation.
 *
 * Each duty is always the upper-switch duty of its bridge leg. A PWM state of
 * ::VOLOOP_PWM_ENABLE with duty 0.0f means that the upper switch remains off
 * and the complementary lower switch remains on. A state of
 * ::VOLOOP_PWM_DISABLED means both switches must be disabled by board code.
 */
typedef struct {
    VOLOOP_DEF_PwmStateTypeDef LeftLegPwmState;  /**< Left complementary bridge-leg state. */
    float LeftLegDuty;                           /**< Left-leg upper-switch duty in [0, 1]. */
    VOLOOP_DEF_PwmStateTypeDef RightLegPwmState; /**< Right complementary bridge-leg state. */
    float RightLegDuty;                          /**< Right-leg upper-switch duty in [0, 1]. */
} PFC_OutputTypeDef;

/**
 * @brief PLL-derived grid half-cycle state.
 */
typedef enum {
    PFC_LINE_ZERO = 0U, /**< PLL sine is within the configured zero-crossing deadband. */
    PFC_LINE_POSITIVE,  /**< Positive grid half-cycle. */
    PFC_LINE_NEGATIVE   /**< Negative grid half-cycle. */
} PFC_LinePolarityTypeDef;

/**
 * @brief Hardware and modulation limits.
 *
 * Every field is required. ::VOLOOP_PFC_Init rejects non-finite or
 * inconsistent limits. The duty limits apply only to the bridge leg currently
 * switching at high frequency; the line-frequency leg is allowed to use an
 * upper-switch duty of 0.0f.
 */
typedef struct {
    float BusOverVoltageThreshold;  /**< Active-state DC-bus over-voltage threshold in volts. */
    float GridOverCurrentThreshold; /**< Active-state absolute grid-current threshold in amperes. */
    float MinHighFrequencyDuty;     /**< Minimum high-frequency upper-switch duty in [0, 1). */
    float MaxHighFrequencyDuty;     /**< Maximum high-frequency upper-switch duty below 1. */
    float ZeroCrossingDeadband;     /**< Absolute PLL sine threshold in [0, 1). */
} PFC_ConfigTypeDef;

/**
 * @brief PFC initialization parameters.
 *
 * The PLL, DC-bus voltage controller, and grid-current controller are expected
 * to run at ::PFC_InitTypeDef::TriggerFrequency. PID configuration validation
 * is delegated to ::VOLOOP_PID_Init.
 *
 * Child initialization objects and configuration are consumed during
 * ::VOLOOP_PFC_Init. Their contents are copied into the PFC handle or child
 * controllers, so they do not need to remain alive afterward.
 */
typedef struct {
    const PLL_InitTypeDef* PLLInit;            /**< Grid PLL initialization. */
    const PID_InitTypeDef* BusVoltagePIDInit;  /**< DC-bus voltage PI initialization. */
    const PID_InitTypeDef* GridCurrentPIDInit; /**< Grid-current PI initialization. */
    const PFC_ConfigTypeDef* Config;           /**< Hardware and modulation limits. */
    float TriggerFrequency;                    /**< Shared control-loop frequency in Hz. */
} PFC_InitTypeDef;

/**
 * @brief PFC runtime state.
 */
typedef enum {
    PFC_RESET = 0U,    /**< Zero-initialized, reset, or deinitialized handle. */
    PFC_DISABLED,      /**< Power output disabled while the PLL continues tracking. */
    PFC_WAIT_PLL,      /**< Output requested, but the PLL is not locked. */
    PFC_RUNNING,       /**< PFC running without current-amplitude saturation. */
    PFC_CURRENT_LIMIT, /**< PFC running at the configured current-amplitude limit. */
    PFC_ERROR          /**< Latched PFC or child-module fault; PLL stopped. */
} PFC_StateTypeDef;

/**
 * @brief PFC latched fault code.
 */
typedef enum {
    PFC_FAULT_NONE = 0U,         /**< No latched fault. */
    PFC_FAULT_INPUT_OVERCURRENT, /**< Grid current exceeded the configured absolute threshold. */
    PFC_FAULT_BUS_OVERVOLTAGE,   /**< DC-bus voltage exceeded the configured threshold. */
    PFC_FAULT_PLL,               /**< The internal PLL reported a runtime failure. */
    PFC_FAULT_INVALID_SAMPLE,    /**< A required measured input was invalid. */
    PFC_FAULT_INVALID            /**< Invalid value returned for an invalid handle. */
} PFC_FaultCodeTypeDef;

/**
 * @brief PFC runtime handle.
 *
 * Applications should treat these members as read-only implementation state
 * and use the public API to operate the controller.
 */
typedef struct {
    PFC_ConfigTypeDef Config;         /**< Copied hardware and modulation limits. */
    PLL_HandleTypeDef PLL;            /**< Grid PLL, active from initialization until a fault. */
    PID_HandleTypeDef BusVoltagePID;  /**< Outer DC-bus voltage PI controller. */
    PID_HandleTypeDef GridCurrentPID; /**< Inner grid-current PI controller. */

    float TriggerFrequency;          /**< Fast control-loop frequency in Hz. */
    float TargetBusVoltage;          /**< Requested DC-bus voltage in volts. */
    float MaxGridCurrent;            /**< Maximum current-amplitude reference in amperes. */
    float CurrentAmplitudeReference; /**< Outer-loop current-amplitude reference in amperes. */
    float CurrentReference;          /**< Signed instantaneous current reference in amperes. */
    float Modulation;                /**< Latest signed modulation value in [-1, 1]. */

    uint8_t ReferenceConfigured; /**< Nonzero after a successful ::VOLOOP_PFC_SetValue call. */
    PFC_LinePolarityTypeDef LinePolarity; /**< Latest PLL-derived grid half-cycle. */
    PFC_StateTypeDef State;               /**< Current PFC runtime state. */
    PFC_FaultCodeTypeDef FaultCode;       /**< Latched fault code. */
} PFC_HandleTypeDef;

/**
 * @brief Initialize a PFC controller and start its PLL.
 *
 * This function validates and copies the configuration, initializes both PI
 * controllers and the PLL, starts the PLL, and enters ::PFC_DISABLED. PFC
 * power output remains disabled until ::VOLOOP_PFC_Start is called.
 *
 * @param handle PFC handle to initialize.
 * @param init Initialization parameters.
 * @return ::VOLOOP_OK on success, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_PFC_Init(PFC_HandleTypeDef* handle, const PFC_InitTypeDef* init);

/**
 * @brief Stop child modules and deinitialize a PFC controller.
 *
 * @param handle PFC handle.
 * @return ::VOLOOP_OK on success, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_PFC_DeInit(PFC_HandleTypeDef* handle);

/**
 * @brief Permit PFC power output after PLL lock.
 *
 * A valid target must have been configured with ::VOLOOP_PFC_SetValue. This
 * function resets both PI controllers and PFC runtime commands, but does not
 * restart or reset the continuously running PLL. The controller enters
 * ::PFC_WAIT_PLL and begins control on a later sync call once the PLL is locked.
 *
 * @param handle PFC handle.
 * @return ::VOLOOP_OK on success, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_PFC_Start(PFC_HandleTypeDef* handle);

/**
 * @brief Disable PFC power output without stopping the PLL.
 *
 * This function resets both PI controllers and PFC runtime commands, enters
 * ::PFC_DISABLED, and leaves the PLL running so phase tracking is preserved.
 *
 * @param handle PFC handle.
 * @return ::VOLOOP_OK on success, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_PFC_Stop(PFC_HandleTypeDef* handle);

/**
 * @brief Clear a latched PFC fault and restart PLL tracking.
 *
 * This operation is valid only in ::PFC_ERROR or ::PFC_DISABLED. For a
 * recoverable protection fault, it resets and restarts the PLL, clears both PI
 * controllers, and returns the PFC to ::PFC_DISABLED. A child PLL already in
 * ::PLL_ERROR requires ::VOLOOP_PFC_DeInit followed by ::VOLOOP_PFC_Init.
 *
 * @param handle PFC handle.
 * @return ::VOLOOP_OK on success, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_PFC_ClearFaultCode(PFC_HandleTypeDef* handle);

/**
 * @brief Set the DC-bus target and grid-current-amplitude limit.
 *
 * Both values must be finite and positive. @p busVoltage must be strictly
 * below the configured bus over-voltage threshold, and @p maxGridCurrent must
 * be strictly below the configured grid over-current threshold. This function
 * may update the reference in any initialized, non-error state.
 *
 * @param handle PFC handle.
 * @param busVoltage Target DC-bus voltage in volts.
 * @param maxGridCurrent Maximum current-amplitude reference in amperes.
 * @return ::VOLOOP_OK on success, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_PFC_SetValue(PFC_HandleTypeDef* handle, float busVoltage,
                                         float maxGridCurrent);

/**
 * @brief Get the current PFC runtime state.
 *
 * @param handle PFC handle.
 * @return Current state, or ::PFC_ERROR if @p handle is NULL.
 */
PFC_StateTypeDef VOLOOP_PFC_GetState(const PFC_HandleTypeDef* handle);

/**
 * @brief Get the latched PFC fault code.
 *
 * @param handle PFC handle.
 * @return Current fault code, or ::PFC_FAULT_INVALID if @p handle is NULL.
 */
PFC_FaultCodeTypeDef VOLOOP_PFC_GetFaultCode(const PFC_HandleTypeDef* handle);

/**
 * @brief Get the continuously running PLL lock state.
 *
 * @param handle PFC handle.
 * @return PLL lock state, or ::PLL_UNLOCKED if @p handle is NULL.
 */
PLL_LockStateTypeDef VOLOOP_PFC_GetPLLLockState(const PFC_HandleTypeDef* handle);

/**
 * @brief Get the latest signed modulation value.
 *
 * The magnitude is the grid-current PI output in [0, 1]. The sign follows the
 * PLL sine half-cycle.
 *
 * @param handle PFC handle.
 * @return Latest signed modulation in [-1, 1], or 0.0f if @p handle is NULL.
 */
float VOLOOP_PFC_GetModulation(const PFC_HandleTypeDef* handle);

/**
 * @brief Get the latest outer-loop current-amplitude reference.
 *
 * @param handle PFC handle.
 * @return Current-amplitude reference in amperes, or 0.0f if @p handle is NULL.
 */
float VOLOOP_PFC_GetCurrentAmplitudeReference(const PFC_HandleTypeDef* handle);

/**
 * @brief Get the latest signed instantaneous grid-current reference.
 *
 * @param handle PFC handle.
 * @return Signed current reference in amperes, or 0.0f if @p handle is NULL.
 */
float VOLOOP_PFC_GetCurrentReference(const PFC_HandleTypeDef* handle);

/**
 * @brief Get the latest PLL-derived grid half-cycle.
 *
 * @param handle PFC handle.
 * @return Latest line polarity, or ::PFC_LINE_ZERO if @p handle is NULL.
 */
PFC_LinePolarityTypeDef VOLOOP_PFC_GetLinePolarity(const PFC_HandleTypeDef* handle);

/**
 * @brief Run one PFC update at the configured fast-loop frequency.
 *
 * The output is written with a safe disabled recommendation before active
 * processing. In ::PFC_DISABLED, only grid-voltage validity and PLL tracking
 * are processed; bus-voltage and grid-current protection are inactive. In an
 * active state, this function validates all measurements, applies protection,
 * updates the PLL, waits for lock, executes both PI control loops, and maps
 * modulation to the left and right bridge legs.
 *
 * When the PLL sine enters the configured zero-crossing deadband, both bridge
 * legs are disabled and the grid-current PI is reset. The PI remains inactive
 * and cleared while the controller remains in the deadband.
 *
 * @param handle PFC handle.
 * @param input Measured grid and DC-bus sample.
 * @param output Left- and right-leg output recommendation.
 * @return ::VOLOOP_OK on success or safe disabled output, ::VOLOOP_ERROR when
 *         a new fault is latched, otherwise a voloop status code.
 */
VOLOOP_StatusTypeDef VOLOOP_PFC_Sync(PFC_HandleTypeDef* handle, const PFC_InputTypeDef* input,
                                     PFC_OutputTypeDef* output);

/** @} */

#endif /* VOLOOP_PFC_H */
